Repository JOML-CI/JOML, pull requests merged in 2020-05, with the labels that each got.

#232 Add test cases for Vector2f/d.perpendicular()
  test/org/joml/test/TestUtil.java
  test/org/joml/test/Vector2dTest.java
  test/org/joml/test/Vector2fTest.java
Labels: improvement

#233 Add Math.clamp(float|double|int) and test cases
  src/org/joml/Math.java
  test/org/joml/test/MathTest.java
Labels: enhancement

#237 Fix parameter ordering in Quaternion#rotateYXZ
  src/org/joml/Quaterniond.java
  src/org/joml/Quaternionf.java
Labels: bugfix

#235 Add AABBi
  src/org/joml/AABBi.java
  src/org/joml/Intersectionf.java
Labels: enhancement

#238 add AABBi/d/f#set(AABBi/d/f source)
  src/org/joml/AABBd.java
  src/org/joml/AABBf.java
  src/org/joml/AABBi.java
Labels: enhancement

#240 Unify AABB/Rectangle intersection test method names
  src/org/joml/AABBd.java
  src/org/joml/AABBf.java
  src/org/joml/AABBi.java
  src/org/joml/Rectangled.java
  src/org/joml/Rectanglef.java
  src/org/joml/Rectanglei.java
  test/org/joml/test/RectangledTest.java
  test/org/joml/test/RectanglefTest.java
  test/org/joml/test/RectangleiTest.java
Labels: enhancement, improvement

#242 Fix find closest point on rectangle
  src/org/joml/Intersectiond.java
  src/org/joml/Intersectionf.java
  test/org/joml/test/IntersectiondTest.java
  test/org/joml/test/IntersectionfTest.java
Labels: bugfix
