Repository JOML-CI/JOML, pull requests merged in 2022-12, with the labels that each got.

#322 Remove background color in package.html
  src/main/java/org/joml/package.html
Labels: improvement

#323 Reorganize files, complete Kotlin extensions
  build.gradle
  src/main/java/org/joml/Matrix3x2f.java
  src/main/java/org/joml/Matrix3x2fc.java
  src/main/java/org/joml/Matrix4d.java
  src/main/java/org/joml/Quaterniond.java
  src/main/java/org/joml/Quaterniondc.java
  src/main/java/org/joml/Quaternionf.java
  src/main/java/org/joml/Quaternionfc.java
  src/main/java/org/joml/Vector2d.java
  src/main/java/org/joml/Vector3d.java
  src/main/java/org/joml/Vector3f.java
  src/main/java/org/joml/Vector3fc.java
  src/main/java/org/joml/Vector4i.java
  src/main/java/org/joml/Vector4ic.java
  src/main/kotlin/org/joml/Extensions.kt
  src/main/kotlin/org/joml/Matrix2d.kt
  src/main/kotlin/org/joml/Matrix2f.kt
  src/main/kotlin/org/joml/Matrix3d.kt
  src/main/kotlin/org/joml/Matrix3f.kt
  src/main/kotlin/org/joml/Matrix3x2d.kt
  src/main/kotlin/org/joml/Matrix3x2f.kt
  src/main/kotlin/org/joml/Matrix4d.kt
  src/main/kotlin/org/joml/Matrix4f.kt
  src/main/kotlin/org/joml/Matrix4x3d.kt
  src/main/kotlin/org/joml/Matrix4x3f.kt
  src/main/kotlin/org/joml/Operators.kt
  src/main/kotlin/org/joml/Quaterniond.kt
  src/main/kotlin/org/joml/Quaternionf.kt
  src/main/kotlin/org/joml/Vector2d.kt
  src/main/kotlin/org/joml/Vector2f.kt
  src/main/kotlin/org/joml/Vector2i.kt
  src/main/kotlin/org/joml/Vector3d.kt
  src/main/kotlin/org/joml/Vector3f.kt
  src/main/kotlin/org/joml/Vector3i.kt
  src/main/kotlin/org/joml/Vector4d.kt
  src/main/kotlin/org/joml/Vector4f.kt
  src/main/kotlin/org/joml/Vector4i.kt
Labels: enhancement, improvement

#326 Fix incorrect sign in Quaternion#getEulerAnglesZYX
  src/main/java/org/joml/Quaterniond.java
  src/main/java/org/joml/Quaternionf.java
  src/test/java/org/joml/test/QuaternionDTest.java
  src/test/java/org/joml/test/QuaternionfTest.java
Labels: bugfix
